### PR TITLE
fix `distutils` deprecation warning

### LINKED ISSUE #158: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
Testing with Python 3.10.4, I get the following deprecation warnings when importing a python library with `PyCall.import_module`:

```
..../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall/python/investigator.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.sysconfig import get_config_var, get_python_version
..../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/pycall-1.4.1/lib/pycall/python/investigator.py:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_config_var, get_python_version
<module 'numpy' from '/usr/local/lib/python3.10/site-packages/numpy/__init__.py'>
```

Changing `distutils.sysconfig` to `sysconfig` at least silences the warning (see linked PR)

### PR DESCRIPTION
**Pull request by c-dilks**
close #158

### CODE REVIEW

**Comment by cboulanger** [comment]
It would be great if this could be merged soon so we get rid of the Deprecation warning. Thank you.

**Comment by c-dilks** [comment]
This PR is ready for review, so it's up to @mrkn to decide.

**Comment by nhorton** [comment]
@mrkn - are you open to additional maintainers to help? We just took on the PyCall dependency and my team is getting nervous with the deprecation warnings. I have both Python and Ruby folks on my team and we would be happy to help.

**Comment by mrkn** [comment]
@c-dilks Thank you very much!

**Pull request merged**
